### ISSUE TITLE
genfstab: command not found

### ISSUE THREAD

**Issue by figgles** [LordRafa/ALARMOnTegraK1#2]
While running the script `archlinux.sh`, it stops with this error:

Downloading and extracting ArchLinuxARM rootfs   /archlinux.sh: line 69: genfstab: command not found
 ...done.

Reading this link makes me wonder if `genfstab` is no longer supported.
https://bbs.archlinux.org/viewtopic.php?id=207690

**Comment by figgles** [comment]
Commenting out the line caused the script to succeed. The system was bootable afterwards.

**Comment by LordRafa** [comment]
Removed on commit ae6da5263831809a842b7b4a2cdf62a2dce61ffb
