### ISSUE TITLE
Nvidia driver from Linux4tegra?

### ISSUE THREAD

**Issue by Axisar** [LordRafa/ALARMOnTegraK1#4]
Hi.
I checked sources and can`t find installation of original nvidia driver
like here https://elinux.org/Jetson/Porting_Arch#Changes_to_nvidia_drivers_Package
What driver will be used after your script?

**Comment by figgles** [comment]
The drivers you are mentioning are proprietary drivers from NVidia and only work with the L4T package (and specific kernel version). From the page you linked:

"This will go over the important steps of installing Arch Linux on the Jetson TK1. Including installing the **kernel, drivers, and configuration from the Linux for Tegra** release provided by NVIDIA."

This uses a much newer kernel. The driver installed by this script will be `nouveau`, i.e. open source one. You can verify this with `lsmod`:

```
[root@alarm alarm]# lsmod
Module                  Size  Used by
nouveau              1728512  0
ttm                    61440  1 nouveau
```

**Comment by LordRafa** [comment]
As @figgles  reply nouveau will be the driver in use
