### ISSUE TITLE
Uboot problem

### ISSUE THREAD

**Issue by hemkr** [LordRafa/ALARMOnTegraK1#6]
![20211117_161601](https://user-images.githubusercontent.com/4699846/142155028-a4d55105-23e3-48eb-a6d5-8dc88926d2f1.jpg)
![9eba4c2aaab661ad4d7a8fab3111c40a](https://user-images.githubusercontent.com/4699846/142155526-d188fb25-33b5-4392-8564-1044decd6f3f.png)

What's the reason?
I installed it on the emmc, but it's not booting.

**Comment by LordRafa** [comment]
Couln't reproduce this
